### ISSUE TITLE
background image not displayed

### ISSUE THREAD

**Issue by ghost** [Nihvel/your_name#17]
I followed the instructions to display the background image. But it doesn't show. What info can I give you to look into this?

**Comment by p3dr0zz** [comment]
Same issue, have the yourname.jpg sitting in /www/backgrounds and it doesn't load.

**Comment by Nihvel** [comment]
I tried to replicate this error but I don't experience what you are describing. 
I also updated HA to the latest version 2024.8.3 because it could be that the newer version introduced this issue, and I was still at the previous 2024.7.x on the instance where I run this theme, but the theme loads the background image just fine.
Also tried with an incognito window (no cache) and that still works.

The theme uses `/local/backgrounds/yourname.jpg` but it's good thing to note, because it might be misleading, that the folder `local` maps to the physical folder `www` in HA. So the path where the image is, `/www/backgrounds/yourname.jpg`, is correct.

**Comment by Al-Girard** [comment]
Thanks for the response!  It seemed to just be a time thing (cache maybe?) but it fixed itself.

So strange, I restarted HA a few times after the install and could not get it to appear.  Left it overnight, came back and it's working.   
 I even double checked to make nothing rebooted or crashed overnight.  Appologies for not replying sooner!

**Comment by Al-Girard** [comment]
The theme was already awesome, but it's far better with the background working :D

**Comment by ghost** [comment]
@Nihvel Are you referring to the filesystem root ("/") when writing "/local/backgrounds" and "/www/backgrounds"?
I created those two folders in every possible location: "/" and under "/homeassistant" but it doesn't work.

versions are:
Core 2024.8.3
Supervisor 2024.08.0
Operating System 13.1
Frontend 20240809.0

**Comment by Nihvel** [comment]
@Mubaer The physical location where you would want to put the image is /www/backgrounds because that's where the theme looks for the image, you got that right.

The www folder is where your `configuration.yaml` is.

```
/homeassistant/configuration.yaml
/homeassistant/www/backgrounds/yourname.jpg
```

The only thing needed for the theme(s) to work is enabling loading them from the themes folder. But you must have done that already, otherwise the theme won't show up among the available themes. This is not only for Your Name. but it's a common HA thing.

```
frontend:
  themes: !include_dir_merge_named themes
```

I still suspect it is a caching issue. Try not only an incognito window, but also to delete your browser cache.

**Comment by ghost** [comment]
It is working now. It was a browser issue. After clearing ALL (!) cached data the background image showed up.
Thanks for the support.
